apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prom-demo
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      containers:
        - image: andrewwebber/learn-rust-prometheus:v0.1.1
          imagePullPolicy: Always
